---
- name: Install node and npm
  hosts: ubuntu
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600 
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm
- name: Deploy nodejs App.
  hosts: ubuntu
  tasks:
    - name: Copy nodejs folder to a server and unpack it there
      unarchive:
        src: /root/gitlab/nodejs/my-app/my-app-0.1.0.tgz
        dest: /root/package
    - name: Install dependencies
      npm:
        path: /root/package/package
    - name: Start the application
      command:
        chdir: /root/package/package/
        cmd: node server 
      async: 1000
      poll: 0
