---
- name: Deploy app in a new namespace
  hosts: local
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present  

    - name: Deploy nginx 
      kubernetes.core.k8s:
        