---
- name: Install docker
  hosts: ec2
  become: yes
  tasks:
    - name: Ensure docker and libxcrypt-compat are installed
      yum: 
        name:
          - docker
          - libxcrypt-compat
        update_cache: yes
        state: present

- name: Install docker compose
  hosts: ec2
  become: yes
  tasks:
    - name: Install docker-compose 
      get_url:
        url: https://github.com/docker/compose/releases/download/1.26.0/docker-compose-{{lookup('pipe','uname -s')}}-{{lookup('pipe','uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x

- name: Start docker 
  hosts: ec2
  become: yes
  tasks:
    - name: Ensure docker is running 
      systemd:
        name: docker
        state: started


- name: Add ec2-user to docker group 
  hosts: ec2
  become: yes
  tasks:
    - name: Add ec2-user to docker group 
      user: 
        name: ec2-user
        groups: docker 
        append: yes 
    - name: Reconnect to server session 
      meta: reset_connection

- name: test docker pull 
  hosts: ec2
  tasks:
    - name: Pull redis
      docker_image:
        name: redis
        source: pull
