---
- name: Install docker
  hosts: ec2
  become: yes
  tasks:
    - name: Ensure docker and libxcrypt-compat are installed
      yum: 
        name:
          - docker
          - libxcrypt-compat
          - python3-pip
        update_cache: yes
        state: present

  
- name: Install docker compose
  hosts: ec2
  become: yes
  tasks:
    - name: Install docker-compose 
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: +x


- name: Start docker 
  hosts: ec2
  become: yes
  tasks:
    - name: Ensure docker is running 
      systemd:
        name: docker
        state: started


- name: Add ec2-user to docker group 
  hosts: ec2
  become: yes
  tasks:
    - name: Add ec2-user to docker group 
      user: 
        name: ec2-user
        groups: docker 
        append: yes 
    - name: Reconnect to server session 
      meta: reset_connection

- name: Start docker containers from docker-compose file
  hosts: ec2
  vars_files:
    - project-vars
  tasks:
    - name: Copy Docker compose
      copy: 
        src: /root/ansible/Ansible/docker-compose.yaml
        dest: /home/ec2-user  
    - name: Docker login
      docker_login:
        registry_url: https://index.docker.io/v1
        username: ibrahimosama
        password: "{{docker_password}}"
    - name: Install docker python module
      pip:
        name: docker
    - name: Start containers from compose 
      community.docker.docker_compose_v2:
        project_src: /home/ec2-user