---
- name: Install java and net-tools
  hosts: ubuntu
  tasks:
    - name: Update repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install Java version 8 
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools 

- name: Download and unpack Nexus installer
  hosts: ubuntu
  tasks:
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: downnload_result
    - debug: msg={{download_result}}
    #- name: Untar Nexus installer
      #unarchive:
        #src: /opt/nexus-3.70.1-02-java8-unix.tar.gz
        #dest: /opt/
        #remote_src: yes
