---
- name: Install docker
  hosts: ec2
  become: yes
  tasks:
    - name: Install docker and libxcrypt-compat
      yum: 
        name:
          - docker
          - libxcrypt-compat
        update_cache: yes
        state: present

- name: Install docker compose
  hosts: ec2
  become: yes
  tasks:
    - name: Install docker-compose 
      get_url:
        url: https://github.com/docker/compose/releases/download/1.26.0/docker-compose-{{lookup('pipe','uname -s')}}-{{lookup('pipe','uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x

- name: Start docker 
  hosts: ec2
  become: yes
  tasks:
    - name: start docker demon 
      systemd:
        name: docker
        state: started