services:
  java-app:
    image: ibrahimosama/my-repo:jma-2.0
    environment:
      - DB_USER=user
      - DB_PWD=pass
      - DB_SERVER=mysql
      - DB_name=my-app-db
    ports:
    - 8080:8080
    container_name: my-java-app

  mysql:
    image: mysql
    ports:
    - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=my-app-db
      - MYSQL_USER=user
      - MYSQL_PASSWPRD=pass
    container_name: mysql
  
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8083:80
    container_name: myadmin
