---
- name: Configure nginx web server
  hosts: ubuntu
  become: true
  become_method: sudo
  tasks:
  - name: install nginx server
    apt:
      name: nginx
      state: latest
  - name: start installed nginux
    service:
      name: nginx
      state: started