---
- name: Configure nginx web server
  hosts: ubuntu
  tasks:
  - name: uninstall nginx server
    apt:
      name: nginx
      state: absent
  - name: stop installed nginux
    service:
      name: nginx
      state: stopped