---
- name: Configure nginx web server
  hosts: ubuntu
  tasks:
  - name: install nginx server
    apt:
      name: nginx
      state: latest
  - name: start installed nginux
    service:
      name: nginx
      state: started